apiVersion: v1
kind: Secret
metadata:
  name: registration-secret
  namespace: petshop-apps
type: Opaque
stringData:
  DB_USER: "petshop"
  DB_PASS: "petshop"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
