apiVersion: v1
kind: Service
metadata:
  name: registration-service
  namespace: petshop-apps
spec:
  selector:
    app: registration-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
